/**
 * QuestDB Built-in Functions
 * Used for:
 * 1. Function highlighting (predefined token class in Monaco)
 * 2. Autocomplete suggestions with CompletionItemKind.Function
 *
 * Note: The parser accepts any identifier as a function name.
 * This list is purely for IDE features (highlighting + completion).
 */
export const functions: string[] = [
  // Math functions
  "abs",
  "acos",
  "asin",
  "atan",
  "atan2",
  "ceil",
  "ceiling",
  "cos",
  "cot",
  "degrees",
  "exp",
  "floor",
  "ln",
  "log",
  "pi",
  "power",
  "radians",
  "round",
  "round_down",
  "round_half_even",
  "round_up",
  "sign",
  "sin",
  "sqrt",
  "tan",

  // Aggregate functions
  "approx_count_distinct",
  "approx_median",
  "approx_percentile",
  "arg_max",
  "arg_min",
  "avg",
  "bit_and",
  "bit_or",
  "bit_xor",
  "bool_and",
  "bool_or",
  "corr",
  "count",
  "count_distinct",
  "covar_pop",
  "covar_samp",
  "first",
  "first_not_null",
  "geomean",
  "ksum",
  "last",
  "last_not_null",
  "max",
  "min",
  "mode",
  "nsum",
  "regr_intercept",
  "regr_slope",
  "spread",
  "spread_bps",
  "stddev",
  "stddev_pop",
  "stddev_samp",
  "string_agg",
  "string_distinct_agg",
  "sum",
  "var_pop",
  "var_samp",
  "variance",
  "vwap",
  "weighted_avg",
  "weighted_stddev",
  "weighted_stddev_freq",
  "weighted_stddev_rel",
  "wmid",

  // Window functions
  "dense_rank",
  "first_not_null_value",
  "first_value",
  "lag",
  "last_value",
  "lead",
  "rank",
  "row_number",

  // Array functions
  "array_avg",
  "array_count",
  "array_cum_sum",
  "array_max",
  "array_min",
  "array_position",
  "array_stddev",
  "array_stddev_pop",
  "array_stddev_samp",
  "array_sum",
  "dim_length",
  "dot_product",
  "flatten",
  "matmul",
  "transpose",

  // String functions
  "base64",
  "concat",
  "ilike",
  "lcase",
  "left",
  "len",
  "length",
  "length_bytes",
  "like",
  "lower",
  "lpad",
  "ltrim",
  "md5",
  "mid",
  "position",
  "quote_ident",
  "regexp_replace",
  "replace",
  "right",
  "rpad",
  "rtrim",
  "sha1",
  "sha256",
  "split_part",
  "starts_with",
  "strpos",
  "substring",
  "to_lowercase",
  "to_uppercase",
  "trim",
  "ucase",
  "upper",

  // Date/Time functions
  "date_trunc",
  "dateadd",
  "datediff",
  "day",
  "day_of_week",
  "day_of_week_sunday_first",
  "days_in_month",
  "extract",
  "hour",
  "interval_end",
  "interval_start",
  "is_leap_year",
  "micros",
  "millis",
  "minute",
  "month",
  "nanos",
  "now",
  "second",
  "sysdate",
  "systimestamp",
  "timestamp_ceil",
  "timestamp_floor",
  "timestamp_sequence",
  "timestamp_shuffle",
  "to_char",
  "to_date",
  "to_pg_date",
  "to_str",
  "to_timestamp",
  "to_timestamp_ns",
  "to_timezone",
  "to_utc",
  "today",
  "tomorrow",
  "week_of_year",
  "year",
  "yesterday",

  // Geospatial functions
  "geo_distance_meters",
  "geo_within_radius_latlon",
  "haversine_dist_deg",
  "make_geohash",
  "within",
  "within_box",
  "within_radius",

  // Type conversion
  "cast",
  "to_long128",
  "to_long256",
  "to_uuid",
  "typeOf",

  // Null handling
  "coalesce",
  "ifnull",
  "isnull",
  "nullif",
  "nvl",

  // Conditional
  "case",
  "greatest",
  "least",

  // Random data generation
  "rnd_bin",
  "rnd_boolean",
  "rnd_byte",
  "rnd_char",
  "rnd_date",
  "rnd_decimal",
  "rnd_double",
  "rnd_double_array",
  "rnd_float",
  "rnd_geohash",
  "rnd_int",
  "rnd_interval",
  "rnd_ipv4",
  "rnd_log",
  "rnd_long",
  "rnd_long256",
  "rnd_short",
  "rnd_str",
  "rnd_symbol",
  "rnd_symbol_weighted",
  "rnd_symbol_zipf",
  "rnd_timestamp",
  "rnd_uuid4",
  "rnd_varchar",

  // Table functions
  "generate_series",
  "long_sequence",
  "read_parquet",
  "parquet_scan",

  // JSON functions
  "json_extract",

  // Network functions
  "netmask",

  // System/Admin functions
  "all_permissions",
  "all_tables",
  "batch",
  "build",
  "commitLag",
  "current_database",
  "current_schema",
  "current_schemas",
  "current_catalog",
  "current_setting",
  "current_user",
  "dump_memory_usage",
  "dump_thread_stacks",
  "export_files",
  "files",
  "flush_query_cache",
  "format",
  "format_type",
  "functions",
  "glob",
  "headers",
  "hydrate_table_metadata",
  "import_files",
  "insertion_point",
  "isOrdered",
  "keywords",
  "l2price",
  "list",
  "materialized_views",
  "maxUncommittedRows",
  "memory_metrics",
  "permissions",
  "query_activity",
  "reader_pool",
  "reload_config",
  "reload_tls",
  "server_conf",
  "server_version",
  "session_user",
  "shift",
  "show",
  "simulate_crash",
  "size_pretty",
  "switch",
  "table_columns",
  "table_partitions",
  "table_storage",
  "table_writer_metrics",
  "tables",
  "touch",
  "version",
  "views",
  "wal_tables",
  "wal_transactions",
  "writer_pool",

  // PostgreSQL compatibility functions
  "pg_advisory_unlock_all",
  "pg_attrdef",
  "pg_attribute",
  "pg_catalog.age",
  "pg_catalog.current_database",
  "pg_catalog.current_schema",
  "pg_catalog.current_schemas",
  "pg_catalog.pg_attrdef",
  "pg_catalog.pg_attribute",
  "pg_catalog.pg_class",
  "pg_catalog.pg_database",
  "pg_catalog.pg_description",
  "pg_catalog.pg_get_expr",
  "pg_catalog.pg_get_keywords",
  "pg_catalog.pg_get_partkeydef",
  "pg_catalog.pg_get_userbyid",
  "pg_catalog.pg_index",
  "pg_catalog.pg_inherits",
  "pg_catalog.pg_is_in_recovery",
  "pg_catalog.pg_locks",
  "pg_catalog.pg_namespace",
  "pg_catalog.pg_roles",
  "pg_catalog.pg_shdescription",
  "pg_catalog.pg_table_is_visible",
  "pg_catalog.pg_type",
  "pg_catalog.txid_current",
  "pg_catalog.version",
  "pg_class",
  "pg_database",
  "pg_description",
  "pg_extension",
  "pg_get_expr",
  "pg_get_keywords",
  "pg_get_partkeydef",
  "pg_index",
  "pg_inherits",
  "pg_is_in_recovery",
  "pg_locks",
  "pg_namespace",
  "pg_postmaster_start_time",
  "pg_proc",
  "pg_range",
  "pg_roles",
  "pg_type",
  "txid_current",

  // Logical operators (also functions in some contexts)
  "and",
  "between",
  "in",
  "not",
  "or",

  // information_schema
  "information_schema._pg_expandarray",
]
